<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title><?php echo $this->splashPage->getTitle(); ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('styles/blueprint/screen.css'); ?>" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('styles/blueprint/print.css'); ?>" media="print" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/css/all.css'); ?>" media="screen" />
	<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/jquery-1.6.4.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/js/main.js'); ?>"></script>
	<!--[if lt IE 8]>
		<link rel="stylesheet" href="<?php echo $this->baseUrl('styles/blueprint/ie.css'); ?>" type="text/css" media="screen, projection" />
	<![endif]-->
	<?php
	    echo $this->headLink();
	    echo $this->headScript();
	?>
</head>
<body>
	<div id="wrapper">
		<div id="header" class="container">
			<div class="logo-box">
				<div class="logo"><?php echo $this->layout()->{"container-2"} ;?></div>
			</div>
			<span class="promo">
				<?php echo $this->layout()->{"container-1"}; ?>
			</span>
			<a href="http://www.unwired.at/" class="powered">powered by Unwired Networks</a>
			<form action="#">
				<fieldset>
					<?php echo $this->languageSelect(true, $this->splashPage);?>
				</fieldset>
			</form>
		</div>
		<div class="visual container">
			<img src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/images/img-visual.jpg');?>" alt="image" width="980" height="460" />
		</div>
		<div id="main" class="container">
			<div class="aside span-6">
				<?php echo $this->layout()->container1; ?>
			</div>
			<div class="span-12">
				<div class="content">
					<div class="content-holder">
						<div class="content-frame">
						<?php echo $this->uiMessage(); ?>
						<?php echo $this->layout()->content; ?>
						</div>
					</div>
				</div>
			</div>
			<div id="sidebar" class="span-6 last">
				<!--<div class="box aside-box">
					<div class="holder">
						<div class="frame">
							<div class="content-area">
								<img src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/images/img-screen.jpg');?>" alt="image description" width="218" height="272" />
							</div>
						</div>
					</div>
				</div>
				-->
				<?php echo $this->layout()->container2; ?>
			</div>
		</div>
		<div id="footer" class="container">
			<a href="<?php echo $this->url(array('forceLayout' => 'mobile'), 'default', false); ?>" class="link-mobile"><?php echo $this->translate('splashpage_link_version_mobile'); ?></a>
		</div>
		<div id="imprint">
			<a href="<?php echo $this->url(array('module' => 'default',
					                                     'controller' => 'index',
					                                     'action' => 'imprint'),
					                               'default',
					                               true); ?>" class="opener"><?php echo $this->translate('splashpage_link_imprint'); ?></a>
		</div>
	</div>
</body>
</html>
