<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<title><?php echo $this->splashPage->getTitle(); ?></title>
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="Mon, 22 Jul 2002 11:11:01 GMT" />
	<meta http-equiv="pragma" content="no-cache" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/mobile/css/all.css'); ?>" />
	<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/jquery-1.6.4.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/mobile/js/jquery.main.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/js/cufon-yui.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('data/templates/' . $this->splashPage->getTemplateId() . '/desktop/js/PFHandbookPro-Thin_200.font.js'); ?>"></script>
	<?php
	    echo $this->headLink();
	    echo $this->headScript();
	?>
	<script type="text/javascript">
			Cufon.replace('h1,h2,h3');
			Cufon.replace('a.opener', {textShadow: '#b2830b 0px 0px, #b2830b 1px 2px'});
			Cufon.replace('.links-widget a', {textShadow: '#d99f0f -1px 1px, #d99f0f 1px -1px'});
			Cufon.replace('a.button', {textShadow: '#d99f0f -1px 1px, #d99f0f 1px -1px'});
			$(document).ready(function(){
				Cufon.replace('a.opener', {textShadow: '#b2830b 0px 0px, #b2830b 1px 2px'});
			});
	</script>
</head>
<body>
	<div id="wrapper">
		<div id="header">

		</div>
		<div id="main">
			<?php echo $this->uiMessage(); ?>
			<ul id="nav" class="accordion">
				<?php
				    $class = "selected";
				    foreach ($this->layout()->contentContainer as $block):
				        if (is_object($block) && $block->getColumn() < 0) {
				            continue;
				        }
				?>
				<li>
					<?php if (is_string($block)): ?>
					     <?php echo $block; ?>
					<?php else :
							$blockContent = (string) $block;

							$blockContent = trim($blockContent);

							$blockContentText = trim(strip_tags($blockContent));

							if (!empty($blockContentText) || ($block->getWidget() == 'Login' && !Zend_Auth::getInstance()->hasIdentity())
							    || in_array($block->getWidget(), array('Iframe','Links'))) :
					?>
					<a href="#" class="opener <?php echo $class; ?>"><?php echo $block->getTitle(); ?></a>
					<div class="slide">
						<div class="content">
					        <?php echo $blockContent; ?>
						</div>
					</div>
					<?php
							endif; // blockContent
						endif;
					?>
				</li>
				<?php
				    $class = '';
				    endforeach;
				?>
				<li>
					<a href="<?php echo $this->url(array('module' => 'default',
					                                     'controller' => 'index',
					                                     'action' => 'imprint'),
					                               'default',
					                               true); ?>" class="opener ajax"><?php echo $this->translate('splashpage_link_imprint'); ?></a>
				</li>
			</ul>
		</div>
		<div id="footer">
			<a href="<?php echo $this->serverUrl() . $this->url(array('forceLayout' => 'desktop'), 'default', false); ?>" class="link-desktop"><?php echo $this->translate('splashpage_link_version_desktop'); ?></a>
		</div>
	</div>
	<script type="text/javascript"> Cufon.now(); </script>
</body>
</html>
