<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/
?>
<?php
    if ($this->content->getContentId()) :
?>
	<input type="hidden" name="content_id" value="<?php echo $this->content->getContentId(); ?>" />
<?php
    endif;
?>
<input type="hidden" name="column" value="<?php echo $this->escape($this->content->getColumn()); ?>"/>
<input type="hidden" name="layout_id" value="<?php echo $this->escape($this->content->getLayoutId()); ?>"/>
<input type="hidden" name="order" value="<?php echo $this->escape($this->content->getOrder()); ?>"/>
<input type="hidden" name="type" value="<?php echo $this->escape($this->content->getType()); ?>"/>
<input type="hidden" name="widget" value="Html"/>
<?php
    $contentData = array();

    foreach ($this->content->getData() as $data) {
        $contentData[$data->getLanguageId()] = $data;
    }
?>

<div id="content" class="tabs span-18 last">
	<ul>
	<?php
	    $templateSettings = $this->template->getSettings();
	    foreach ($templateSettings['language_ids'] as $languageId) :
    ?>
		<li><a href="#language-<?php echo $languageId; ?>"><?php echo $this->languages[$languageId]->getName();?></a></li>
    <?php
	    endforeach;
	?>
	</ul>
	<?php
	    foreach ($templateSettings['language_ids'] as $languageId) :
		    if (!isset($contentData[$languageId])) {
		        $data = new Captive_Model_ContentData();
		        $data->setLanguageId($languageId);
		        $contentData[$languageId] = $data;
		    }
	?>
	<div id="language-<?php echo $languageId; ?>" class="content">
		<div class="formelement span-16 last">
			<label for="title-<?php echo $languageId; ?>"><?php echo $this->translate('widget_html_admin_title');?>:</label>
			<input class="span-12 last" type="text" name="content[<?php echo $languageId; ?>][title]"
			id="title-<?php echo $languageId; ?>" value="<?php echo $contentData[$languageId]->getTitle(); ?>" />
		</div>
		<div class="formelement span-16 last">
			<label for="content-<?php echo $languageId; ?>"><?php echo $this->translate('widget_html_admin_content');?>:</label>
			<div class="span-16 last">
    			<textarea class="span-16 last" name="content[<?php echo $languageId; ?>][content]"
    			id="content-<?php echo $languageId; ?>"><?php echo $contentData[$languageId]->getContent(); ?></textarea>
			</div>
		</div>
	</div>
	<?php
	    endforeach;
	?>
</div>
