<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jquery.sparkline.min.js'));
	$this->headScript()->appendFile($this->httpScheme() . '://maps.googleapis.com/maps/api/js?sensor=false');
	$markerClusteringLevel = 0;

	if (isset($this->systemSettings['node_map_cluster_level']) && ($this->systemSettings['node_map_cluster_level']->getValue() > 0)) {
	    $markerClusteringLevel = (int) $this->systemSettings['node_map_cluster_level']->getValue();
	    $this->headScript()->appendFile($this->httpScheme() . '://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js');
	}

	$this->headScript()->captureStart();
	
	// render generated map 
	echo $this->jscript;
?>
		<?php if ($markerClusteringLevel > 0) :?>
		var markerClusterer = new MarkerClusterer(map, markers, {maxZoom: <?php echo $markerClusteringLevel; ?>});
		<?php
		     endif;
		     if (isset($this->currentUser)) :
		?>
		loadNetworkStatistics();
		<?php endif; ?>
	});

<?php
	$this->headScript()->captureEnd();
?>
<?php if (isset($this->currentUser)) : ?>
<form method="get" action="<?php echo $this->url(array('module' => 'default',
													   'controller' => 'index',
													   'action' => 'nodesearch'),
												null,
												true); ?>">
<table class="listing">
	<thead>
	<tr>
			<th><?php echo $this->translate('nodes_index_index_name');?></th>
			<th><?php echo $this->translate('nodes_index_index_mac');?></th><th></th>
			</tr>
			<tr>
<th><input type="text" name="name" value="<?php echo $this->filter['name']; ?>" /></th>
<th><input type="text" name="mac" value="<?php echo $this->filter['mac']; ?>" /></th>

<th class="tools">
			<a name="index_index" class="icon filter"><?php echo $this->translate('nodes_index_index_button_filter'); ?></a>
			</th>

</tr>
</thead>
</table>
</form>
<?php endif; ?>
<div id="nodemap"></div>
<?php if (isset($this->currentUser)) :?>
<div id="networkstats">
	<div><strong><?php echo $this->translate('default_index_index_statistics')?>:</strong>
	<ul>
		<li><strong><?php echo $this->translate('default_index_index_devices')?>:</strong>
    		<ul>
    			<li><strong><?php echo $this->translate('default_index_index_devices_total')?></strong>: <span id="devicestotal"><?php echo $this->networkStats->getDevicesTotal(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_devices_online')?></strong>: <span id="devicesonline"><?php echo $this->networkStats->getDevicesOnline(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_devices_offline')?></strong>: <span id="devicesoffline"><?php echo $this->networkStats->getDevicesOffline(); ?></span></li>
    		</ul>
		</li>
    	<li>
    		<strong><?php echo $this->translate('default_index_index_users')?>:</strong>
    		<ul>
    			<li><strong><?php echo $this->translate('default_index_index_users_total')?></strong>: <span id="userstotal"><?php echo $this->networkStats->getUsersTotal(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_users_online')?></strong>: <span id="usersonline"><?php echo $this->networkStats->getUsersOnline(); ?></span></li>
    			<li><strong><?php echo $this->translate('default_index_index_users_garden')?></strong>: <span id="usersgarden"><?php echo $this->networkStats->getUsersGarden(); ?></span></li>
    		</ul>
    	</li>
	</ul>
	</div>
	<div>
		<strong><?php echo $this->translate('default_index_index_bandwidth')?>:</strong>
		<ul>
			<li><strong><?php echo $this->translate('default_index_index_bandwidth_down')?>:</strong> <span id="bandwidthdown">0</span> <span id="networkgraphdown" class="span-13 last" style="float:right; text-align: right;"></span></li>
			<li><strong><?php echo $this->translate('default_index_index_bandwidth_up')?>:</strong> <span id="bandwidthup">0</span> <span id="networkgraphup" class="span-13 last" style="float:right; text-align: right;"></span></li>
		</ul>
	</div>
	<!-- <div><strong><?php echo $this->translate('default_index_index_bandwidth_up')?>:</strong> <span id="bandwidthup">0</span> <span id="networkgraphup" class="span-13 last" style="float:right; text-align: right;"></span></div>
	<div><strong><?php echo $this->translate('default_index_index_bandwidth_down')?>:</strong> <span id="bandwidthdown">0</span> <span id="networkgraphdown" class="span-13 last" style="float:right; text-align: right;"></span></div> -->
</div>
<?php endif; ?>
