<h1><?php
	if ($this->entity->getReportGroupId()) {
		echo $this->translate('report_group_title_edit').' '.$this->entity->getTitle();
	} else {
		echo $this->translate('report_group_title_add');
	}
?></h1>
<?php
	$this->headScript()->appendFile($this->baseUrl('scripts/jstree/jquery.jstree.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/jstree/themes/default/style.css'));

	$groupsAssigned = $this->entity->getGroupsAssigned();

	if (empty($groupsAssigned)) {
		$groupsAssigned = $this->currentUser->getGroupsAssigned();
		$groupsAssigned = array_slice($groupsAssigned, 0, 1, true);
	}

	$this->headScript()->captureStart();

?>
var adminGroups = <?php echo Zend_Json::encode($this->currentUser->getGroupsAssigned());?>;
var groupsAssigned = <?php echo Zend_Json::encode($groupsAssigned);?>;
var innerCountMin = <?php echo $this->entity->getCodeTemplate()->getInnerCountMin();?>;
var innerCountMax = <?php echo $this->entity->getCodeTemplate()->getInnerCountMax();?>;
var innerCountDefault = <?php echo $this->entity->getCodeTemplate()->getInnerCountDefault();?>;

$(function () {
	$("label[for=groups_assigned]").siblings('label').remove();
	$("label[for=groups_assigned]").after($('.grouptree'));
	$("label[for=available_roles]").parent().hide();

	var init_select = new Array();

	$.each(groupsAssigned, function (idx, data) {
		init_select.push('group_' + idx);
	});

	groupIds = [];

    $(".grouptree")
        .jstree({
            "plugins" : ["themes","html_data","ui"],
            "core" : { "initially_open" : init_select },
            "ui" : { select_multiple_modifier: 'on',
            		 disable_selecting_children: true,
					 select_limit : -1,
					 "initially_select" : init_select
					}
        })
        .bind("select_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			if (groupIds.indexOf(groupId) == -1) {
				groupIds.push(groupId);

				var newRole = $("label[for=available_roles]").parent().clone();

				$(newRole).children('label').attr('for', 'selgrp' + groupId)
											.html(data.rslt.obj.children('a:first').text() + ' ');

				$(newRole).children('input').attr('id', 'selgrp' + groupId)
											 .attr('name', 'groups_assigned[' + groupId + ']')
											 .val(groupId);

				$("label[for=available_roles]").parent().before(newRole);

				newRole.show();
			}
	     })
        .bind("deselect_node.jstree", function (event, data) {
			var groupId = data.rslt.obj.attr("id").replace(/[^\d]+/gi,'');

			var idx = groupIds.indexOf(groupId);

			if (idx != -1) {
				groupIds.splice(idx, 1);
				$('#selgrp'+groupId).parent().remove();
			}
	     });


	  $('#date_relative').change(function(){
        if (!$(this).is(':checked')) {
        	$(this).parent().next().show().find('select:first').change();
        } else {
        	$(this).parent().next().hide().next().show().next().show();
        }
	  });

	  $('#timeframe').change(function() {
	  	if ($(this).val() == 'custom') {
	  		$(this).parent().next().show().next().show();
	  	} else {
	  		$(this).parent().next().hide().next().hide();

			var dateFrom = new Date();
			var dateTo = new Date();

	  		switch ($(this).val()) {
	  			case 'yesterday':
	  				dateFrom = new Date(dateFrom.getTime()-24*3600*1000);
	  				dateTo.setTime(dateFrom.getTime());
	  			break;

	  			case 'lastweek':
					/**
					 * @todo Fix if date is less than 7
					 */
					dateFrom.setDate(dateFrom.getDate()-7);
	  			case 'currweek':
					var dayOfWeek = dateFrom.getDay();

					if (dayOfWeek == 0) {
						dateFrom.setTime(dateFrom.getTime()-6*24*3600*1000);
					} else {
						dayOfWeek = dayOfWeek-1;
						dateFrom.setTime(dateFrom.getTime()-dayOfWeek*24*3600*1000);
					}

					dateTo.setTime(dateFrom.getTime()+6*24*3600*1000);
					//dateTo.setDate(dateFrom.getDate()+6);
	  			break;

	  			case 'lastmonth':
					if (dateFrom.getMonth() == 0) {
						dateFrom.setFullYear(dateFrom.getFullYear()-1);
						dateFrom.setMonth(11);
					} else {
						dateFrom.setMonth(dateFrom.getMonth()-1);
					}

	  			case 'currmonth':
					dateFrom.setDate(1);
					dateTo.setTime(dateFrom.getTime());
					if (dateTo.getMonth() == 11) {
						dateTo.setYear(dateTo.getYear()+1);
						dateTo.setMonth(0);
					} else {
						dateTo.setMonth(dateTo.getMonth()+1);
					}

					dateTo.setTime(dateTo.getTime()-24*3600*1000);
	  			break;

	  			case 'lastyear':
					dateFrom.setFullYear(dateFrom.getFullYear()-1);

	  			case 'curryear':
					dateFrom.setDate(1);
					dateFrom.setMonth(0);
					dateTo.setTime(dateFrom.getTime());
					dateTo.setMonth(11);
					dateTo.setDate(31);
	  			break;
	  		}

		  	dateFrom.setHours(0);
			dateFrom.setMinutes(0);
			dateFrom.setSeconds(0);
			dateTo.setHours(23);
			dateTo.setMinutes(59);
			dateTo.setSeconds(0);
	  	}

	  	$('#date_from').datetimepicker('setDate', dateFrom);
	  	$('#date_to').datetimepicker('setDate', dateTo);
	  });

	  $('#report_type').change(function(){
	  	if ($(this).val() == 0) {
	  		$(this).parent().next().hide();
	  	} else {
	  		$(this).parent().next().show();
	  	}
	  });

	  $('#date_relative').change();
	  $('#report_type').change();

	  $('#date_from').change(filterInnerInterval);
	  $('#date_to').change(filterInnerInterval);

	  $('#date_to').change();

	  $('#email').before('<input type="text" id="email_search" class="span-5" />');
	  $('#email_search').autocomplete({
			source: "<?php echo $this->url(array('module' => 'users',
			                                     'controller' => 'admin',
			                                     'action' => 'autocomplete',
			                                     'field' => 'email'));?>",
			minLength: 3,
			select: function( event, ui ) {
				if (!ui.item) {
					return;
				}

				$('#email').val(($('#email').val() + ',' + ui.item.value).trim(','));
				$('#email_search').val('');
			}
		});
});

function filterInnerInterval()
{
  	var timeDiff = ($('#date_to').datetimepicker('getDate').getTime()-$('#date_from').datetimepicker('getDate').getTime())/60000;

	var defaultInnerCountDiff = 9999999999999;

  	$('#inner_interval option').each(function(){

  		var innerCount = timeDiff / parseInt($(this).val());
  		if (parseInt($(this).val()) > timeDiff || (innerCountMin > 0 && innerCount < innerCountMin) || (innerCountMax > 0 && innerCount > innerCountMax)) {
  			$(this).attr('disabled','disabled');
  		} else {
  			$(this).removeAttr('disabled');

  			if (innerCountDefault > 0 && defaultInnerCountDiff > Math.abs(defaultInnerCountDiff - innerCount)) {
  				defaultInnerCountDiff = Math.abs(defaultInnerCountDiff - innerCount);
  				$('#inner_interval').val($(this).val());
  				$(this).attr('selected','selected');
  			}
  		}
  	});

    if (innerCountMin > 0) {
    	$('#inner_interval option:first').removeAttr('disabled');
    	if ($('#inner_interval option:selected').is(':disabled')) {
  			$('#inner_interval').val(0);
  		}
    }
}

<?php
	$this->headScript()->captureEnd();


	echo $this->form;

	if ($this->entity->getCodeTemplate()->isCapable(Reports_Model_CodeTemplate::CAP_GLOBAL)) :
?>

<div class="grouptree span-8">
	<?php echo $this->tree($this->rootGroup, null, array('prefix' => 'group_')); ?>
</div>

<?php
    endif;
?>