<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<?php if (!isset($this->pdf)) :?>
<a href="<?php echo $this->url(array('module' => 'reports'), null, true); ?>"><?php echo $this->translate('report_index_heading'); ?></a> &raquo;
<a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'id' => $this->parent->getCodetemplateId()), null, true);
        ?>">Reports for <?php echo $this->parent->getCodeTemplate()->getTitle();?> </a>
    <?php if (!isset($this->instant)) :?>
     &raquo;
    <a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'action' => 'reports',
                                     'id' => $this->parent->getReportGroupId()), null, true);
        ?>"><?php echo $this->parent->getTitle(); ?> Results</a> &raquo;
    <a href="<?php echo $this->url(array('module' => 'reports',
                                     'controller' => 'group',
                                     'action' => 'view',
                                     'id' => $this->report->getItemId()), null, true);
        ?>"><?php echo $this->translate('report_group_heading_result'); ?>  at <?php echo $this->report->getDateAdded(); ?></a>
    <?php endif; // instant?>
<?php endif; // pdf?>
<br /><br />
<h1><?php echo $this->translate('report_group_heading_result'); ?> <?php echo $this->parent->getTitle(); ?> at <?php echo $this->report->getDateAdded(); ?></h1>
<?php
    if (!isset($this->pdf)) :
    $request = Zend_Controller_Front::getInstance()->getRequest();
?>
<div class="buttons span-18">
	<a class="button small blue" href="<?php echo $this->url(array_merge($request->getParams(), array('format' => 'csv')), 'default', false);?>"><span><?php
	    echo $this->translate('report_group_button_csv');
	?></span></a>
<!--
	<a class="button small blue" href="<?php echo $this->url(array_merge($request->getParams(), array('format' => 'pdf')), 'default', false);?>"><span><?php
	    echo $this->translate('report_group_button_pdf');
	?></span></a>  -->
</div>
<?php endif; // pdf?>
<table width="100%" class="listing">
<tr>
	<th colspan="4"><?php echo $this->translate('report_result_parameters'); ?></th>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_description'); ?></td><td colspan="3"><?php echo $this->parent->getDescription(); ?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_datefrom'); ?></td><td><?php echo $this->parent->getDateFrom();?></td><td><?php echo $this->translate('report_result_parameters_dateto'); ?></td><td><?php echo $this->parent->getDateTo();?></td>
</tr>
<tr>
	<td><?php echo $this->translate('report_result_parameters_devicegroups'); ?></td><td colspan="3"><?php echo str_replace("\n", ", ", $this->parent->getGroupsAssignedFormatted());?></td>
</tr>
</table>

<h3>Results</h3>

<?php


$acl = Zend_Registry::get ( 'acl' );

?>


<?php if (isset($this->data->graphics) && !empty($this->data->graphics)): ?>
	<script type="text/javascript">
	google.load("visualization", "1", {packages:["corechart"]});
	<?php foreach ($this->data->graphics as $key => $value): ?>
	google.setOnLoadCallback(drawChart<?php echo $key?>);
    function drawChart<?php echo $key?>() {
		var data = new google.visualization.DataTable();
		<?php foreach ($value->headers as $k => $v): ?>
		data.addColumn(<?php if (isset($value->rows[0][$k]) && is_numeric($value->rows[0][$k])): ?>"number"<?php else: ?>"string"<?php endif; ?>, "<?=$this->translate($v)?>");
		<?php endforeach; ?>

                data.addRows([
                <?php foreach ($value->rows as $k => $v):
                        echo ($k==0?"":",").json_encode($v)."\n";
                endforeach; ?>
                ]);

		var chart = new google.visualization.<?=isset($value->type)?$value->type:"PieChart"?>(document.getElementById("chart_div<?php echo $key ?>"));
		chart.draw(data, {width: <?=isset($value->width)?$value->width:"750"?>, height: <?=isset($value->height)?$value->height:"500"?>, title: "<?=$this->translate($value->name).' '.(isset($depth)?$depth:"")?>"<?=isset($value->nativeOptions)?','.$value->nativeOptions:''?>});
	}
	<?php endforeach; ?>
	</script>

	<?php foreach ($this->data->graphics as $key => $value): ?>
	<div id="chart_div<?php echo $key; ?>" style="float: left;"></div>
	<?php endforeach; ?>
	<div style="clear: both;"></div>
<?php endif; ?>

<?php if (isset($this->data->tables) && (is_array($this->data->tables) || is_object($this->data->tables))): ?>
	<?php foreach ($this->data->tables as $key => $value):
		$ttype= isset($value->type) ? $value->type : "table";
		if (!$ttype) $ttype="table"; ?>
		<?php if (($ttype=="both") || ($ttype=="graph")):
			$name=(isset($value->name)?$value->name:'unnamed');
			//prepare chartoptions array
			if (isset($value->chartOptions)) $opt=$value->chartOptions;
			else $opt=array();
			if (!isset($opt->depths)) $depth_list=false;
			else if (is_array($opt->depths)) $depth_list=$opt->depths;
			else $depth_list=array($opt->depths);
			$ccnt=0;
			//foreach ($depth_list as $depth):
				$ccnt++;
			?>
			<script type="text/javascript">
			google.load("visualization", "1", {packages:["corechart"]});
			google.setOnLoadCallback(drawChart_<?=$ccnt?>_<?php echo $key?>);
	    		function drawChart_<?=$ccnt?>_<?php echo $key?>() {
				var data = new google.visualization.DataTable();

				<?php if (isset($opt->switchAxes) && $opt->switchAxes) {
					$x=1;$cells="";$Y=0;
					echo "data.addColumn('string','name');\n";
					foreach ($value->rows as $k => $v) {
						if ((!$depth_list||!isset($v->depth)||array_search($v->depth,$depth_list)!==false) && (!isset($v->device)||$v->device==0) ) {
							$y=0;
	                	        		foreach ($v->data as $kk => $vv) {
								if ($y==0) {
									echo "data.addColumn('number','".$vv."');\n";
								}
								else if ($y>=2) $cells.="data.setCell(".($y-2).",$x,".(1*$vv).");\n";
								$y++;
							}
							if ($y>$Y) $Y=$y;
							$x++;
						}
					}
					echo "data.addRows(".($Y-2).");\n".$cells;
					$x=0;

					foreach ($value->colDefs[count($value->colDefs)-1] as $k => $v) {
						if ($x>1) echo "data.setCell(".($x-2).",0,'".(isset($v->name)?str_replace("<br/>","",$v->name):'unnamed')."');\n";
						$x++;
					}
				}
				else { ?>
					<?php foreach ($value->colDefs[count($value->colDefs)-1] as $k => $v):
						$cname=(isset($v->name)?$v->name:'unnamed');
					?>
					data.addColumn(<?php if ( isset($value->rows) && isset($value->rows[0]) && isset($value->rows[0]->data) && is_array($value->rows[0]->data) && isset($value->rows[0]->data[$k]) && is_numeric($value->rows[0]->data[$k])): ?>"number"<?php else: ?>"string"<?php endif; ?>, "<?=/*$this->translate*/($cname)?>");
					<?php endforeach; ?>


		                	data.addRows([
        		        	<?php $rii=0; foreach ($value->rows as $k => $v):?>
						<?php if ((!$depth_list||!isset($v->depth)||array_search($v->depth,$depth_list)!=false) && (!isset($v->device)||$v->device==0) ):?>
	                	        		<?=($rii++==0?"":",")?>[<?php foreach ($v->data as $kk => $vv): echo ($kk==0?"":",").($vv==""?0:(is_numeric($vv)?$vv:'"'.$vv.'"')); endforeach; ?>]
						<?php endif; ?>
	                		<?php endforeach; ?>
        	        		]);
				<?php } ?>

				var chart = new google.visualization.<?=isset($opt->type)?$opt->type:"PieChart"?>(document.getElementById("chart_div_<?=$ccnt?>_<?php echo $key ?>"));
				chart.draw(data, {width: <?=isset($opt->width)?$opt->width:"350"?>, height: <?=isset($opt->height)?$opt->height:"300"?>, title: "<?=$this->translate($name)?>"<?=isset($opt->nativeOptions)?','.$opt->nativeOptions:''?>});
			}
			</script>
			<div id="chart_div_<?=$ccnt?>_<?php echo $key; ?>" style="float: left;"></div>
			<?php //endforeach; /*depth_list*/?>
		<?php endif; /*chart*/?>
		<?php if (($ttype=="both") || ($ttype=="table")):?>
			<table class="listing">
			<?php foreach ($value->colDefs as $kk => $vv): ?>
			<tr>
					<?php foreach ($value->colDefs[$kk] as $k => $v): ?>
					<?php if (is_object($v)):?>
						<th
							<?php if (isset($v->class)): ?>class="<?php echo $v->class?>"<?php endif; ?>
							<?php if (isset($v->width)): ?>width="<?php echo $v->width?>"<?php endif; ?>
							<?php if (isset($v->height)): ?>height="<?php echo $v->height?>"<?php endif; ?>
							<?php if (isset($v->rowspan)): ?>rowspan="<?php echo $v->rowspan?>"<?php endif; ?>
							<?php if (isset($v->colspan)): ?>colspan="<?php echo $v->colspan?>"<?php endif; ?>
						><div <?php if (isset($v->iclass)): ?>class="<?php echo $v->iclass?>"<?php endif; ?>><?=(isset($v->translatable) && $v->translatable)?$this->translate($vv->data):$v->name?></div></th>
					<?php else: ?>
						<th><?php echo $this->translate($v); ?></th>
					<?php endif; ?>
					<?php endforeach; ?>
			</tr>
			<?php endforeach; ?>
			<?php if (isset($value->rows)): ?>
				<?php foreach ($value->rows as $k => $v): 
					if (isset($v->url)) $url=$v->url;
					else $url=false;
				?>
				<tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
					<?php
					/*if (is_array($v->data)) */foreach ($v->data as $kk => $vv):

					if ($url) {
						$vv='<a href="'.$url.'">'.$vv.'</a>';
						$url=false;
					}

				    	if (isset($v->class) && is_object($v->class)) {
					        $v->class = (array) $v->class;
				    	}
					?>

					<td class="<?php echo (isset($v->class[$kk]))? $v->class[$kk]:'';?>" <?php if (is_object($vv) && isset($vv->rowspan)): ?>rowspan="<?php echo $vv->rowspan?>"<?php endif; ?> <?php if (is_object($vv) && isset($vv->colspan)): ?>colspan="<?php echo $vv->colspan?>"<?php endif; ?>>
					<?php if (is_object($vv)):?>
						<?php echo (isset($vv->translatable) && $vv->translatable)?$this->translate($vv->data):$vv->data?>
					<?php else: ?>
						<?php echo $vv?>
					<?php endif; ?>
					</td>
					<?php endforeach; ?>
				</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			</table>
		<?php endif; ?>
	<?php endforeach; ?>
<?php endif; ?>
