<?php
/**
* Unwired AA GUI
*
* Author & Copyright (c) 2011 Unwired Networks GmbH
* alexander.szlezak@unwired.at
*
* Licensed under the terms of the Affero Gnu Public License version 3
* (AGPLv3 - http://www.gnu.org/licenses/agpl.html) or our proprietory
* license available at http://www.unwired.at/license.html
*/
?>
<h1><?php
    if (isset($this->splashPage)) {
	    echo sprintf($this->translate('captive_index_edit_heading_edit'), $this->splashPage->getTitle());
    } else {
        echo sprintf($this->translate('captive_template_edit_heading_edit'), $this->template->getName());
    }

    $settings = $this->template->getSettings();

    $this->contents = $this->contentsToTemplateLayout($this->contents, $this->template);
?></h1>
<?php
    $this->headStyle('.column { padding-top: 5px; min-height:50px; padding-bottom: 5px; margin-bottom: 10px; margin-right: 8px}
				  	  .portlet { margin: 0 5px 10px 5px; }
					  .portlet-header { cursor: move; margin: 2px; padding-bottom: 4px; padding-left: 0.2em; }
					  .portlet-header .ui-icon { cursor: pointer; float: right; }
					  .portlet-content { padding: 0.4em; }
					  .ui-tabs-panel { padding: 10px !important; }
					  .ui-sortable-placeholder { margin: 0 5px 10px 5px;border: 1px dotted black; visibility: visible !important; height: 80px !important; }
					  .ui-sortable-placeholder * { visibility: hidden; }');

	$this->headScript()->appendFile($this->baseUrl('scripts/fancybox/jquery.fancybox-1.3.4.pack.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('scripts/fancybox/jquery.fancybox-1.3.4.css'));
    $this->headScript()->appendFile($this->baseUrl('scripts/nicedit/nicEdit.js'));
    $this->headScript()->captureStart();
?>
	$(document).ready(function() {
		$('div.tabs').tabs();

		$(".column:not(.special)").sortable({
			connectWith: ".column:not(.special)",
			placeholder: "ui-sortable-placeholder ui-state-highlight ui-corner-all",
			distance: 15,
			items: ".portlet:not('.terms'):not('.imprint')"
		});

		$(".portlet").addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
			.find( ".portlet-header" )
				.addClass( "ui-widget-header ui-corner-all" )
				.prepend( "<span class='ui-icon ui-icon-minusthick'></span>")
				.end()
			.find( ".portlet-content" );

		$(".portlet-header .ui-icon").click(function() {
			$( this ).toggleClass( "ui-icon-minusthick" ).toggleClass( "ui-icon-plusthick" );
			$( this ).parents( ".portlet:first" ).find( ".portlet-content" ).toggle();
		});

		$(".column").disableSelection();

		$('#fancybox-content a.cancel').live('click', function(){
			$.fancybox.close();
			return false;
		});
		$('#fancybox-content a.save').live('click', function(){

			var postVars = $('#fancybox-content form:first').serialize();
			$('#fancybox-content form:first').find('input, textarea, select').attr('disabled','disabled');

			$.fancybox.showActivity();

			$.ajax({
				url: $('#fancybox-content form:first').attr('action'),
				data: postVars,
				cache: false,
				type: 'POST',
				success: function(data){

					$.fancybox.hideActivity();
					$.fancybox.close();
				},
				error: function(data){
					alert('There was an error saving the information!');
					$('#fancybox-content form:first').find('input, textarea, select').removeAttr('disabled');

					$.fancybox.hideActivity();
				},
			})
			return false;
		});

		$('a.icon.edit').live('click',function(){
			$.fancybox.showActivity();
			var column = $(this).parents(".column:first").attr('id').replace(/[^0-9]/gi,'');

			if (!column.length) {
				column = 0;
			}

			$.ajax({
				url: '<?php echo $this->url(array('module' => 'captive',
				                                  'controller' => 'content',
				                                  'action' => 'edit',
				                                  'splashId' => (isset($this->splashPage) ? $this->splashPage->getSplashid() : null),
				                                  'templateId' => $this->template->getTemplateId()), 'default', true);?>/column/' + column + '/id/' + $(this).prev().val(),

				'success' : function(data){

					$.fancybox({
						content: data,
						modal: false,
						autoDimensions: true,
						hideOnOverlayClick: false,
						showCloseButton: true,
						onComplete: function() {
							$('#fancybox-content').find('.tabs').tabs();
							$.fancybox.resize();
							$.fancybox.center();
						}
					});
				},
				'error' : function(data) {
					alert('There was an error saving the widget');
					$.fancybox.hideActivity();
				}
			})

		});

		$('a.icon.add').click(function(){
			var column = $(this).parents(".column:first").attr('id').replace(/[^0-9]/gi,'');

			if (!column.length) {
				column = 0;
			}
			$('body').append('<div id="dialogadd" />');
			$('#dialogadd').dialog({
				modal: true,
				title: '<?php echo $this->translate('content_edit_widget_add_title'); ?>',
				closeOnEscape: false,
				open: function(event, ui) {
					$('#dialogadd').append('<div id="widgetSet">'+
                                        		'<input type="radio" id="Html" value="Html" name="widget" checked="checked" /><label for="Html">Html</label>'+
                                        		'<input type="radio" id="Links" value="Links" name="widget" /><label for="Links">Links</label>'+
                                        		'<input type="radio" id="Iframe" value="Iframe" name="widget" /><label for="Iframe">Iframe</label>'+
                                        		'<input type="radio" id="Login" value="Login" name="widget" /><label for="Login">Login</label>'+
                                        	'</div>');
					$('#widgetSet').buttonset();
				},
				close: function(){
					$(this).dialog('destroy');
					$('#dialogadd').remove();
				},
				buttons: {
					'<?php echo $this->translate('content_edit_button_add'); ?>' : function() {
						var addDialog = this;
						$.fancybox.showActivity();

						$.ajax({
							url: '<?php echo $this->url(array('module' => 'captive',
							                                  'controller' => 'content',
							                                  'action' => 'add',
							                                  'splashId' => (isset($this->splashPage) ? $this->splashPage->getSplashid() : null),
							                                  'templateId' => $this->template->getTemplateId()), 'default', true);?>/column/' + column + '/widget/' + $('#widgetSet input:checked').val(),

							'success' : function(data){

								$.fancybox({
									content: data,
									modal: false,
									autoDimensions: true,
									hideOnOverlayClick: false,
									showCloseButton: true,
									onComplete: function() {
										$('#fancybox-content').find('.tabs').tabs();
										$.fancybox.resize();
										$.fancybox.center();
									}
								});

								$(addDialog).dialog('close');
							},
							'error' : function(data) {
								alert('There was an error adding the widget');
								$(addDialog).dialog('close');
							}
						})
					},
					'<?php echo $this->translate('content_edit_button_cancel'); ?>' : function() {
						$(this).dialog('close');
					}
				}
			});
		});

	});
<?php
    $this->headScript()->captureEnd();
?>
<div class="span-19 last">
	<div class="tabs span-19 last">
		<ul>
			<li><a href="#desktop"><?php echo $this->translate('captive_content_tab_desktop'); ?></a></li>
			<li><a href="#mobile"><?php echo $this->translate('captive_content_tab_mobile'); ?></a></li>
		</ul>
		<div id="desktop" class="span-19 last">
  <?php
      /**
       * Reorder columns so main is in the middle
       *
       * @todo Use template file to find column positions
       */
      $colCount = count($this->contents);
      $specialColumn = null;

      if (array_key_exists('special', $this->contents)) {
          $colCount--;
          $specialColumn = $this->contents['special'];
          unset($this->contents['special']);
      }

      $mainCol = $this->contents['main'];
      $colCount--;

      unset($this->contents['main']);

      $mobileContent = array();

      $newColumnOrder = array();
      if ($specialColumn !== null) {
          $newColumnOrder['special'] = $specialColumn;
          $mobileContent['special'] = array();
      }

      $mobileContent['main'] = array();

      $newColumnOrder[key($this->contents)] = array_shift($this->contents);
      $newColumnOrder['main'] = $mainCol;
      $newColumnOrder = $newColumnOrder + $this->contents;

      $this->contents = $newColumnOrder;

      unset($specialColumn, $mainCol, $newColumnOrder);

      foreach ($this->contents as $column => $columnContents) :
      ?>
	  <div id="desktop-column-<?php echo $column; ?>" class="column ui-widget <?php echo $column; ?> ui-widget-content ui-helper-clearfix ui-corner-all span-<?php if ($column == 'special') echo '18 last'; else echo '6'; ?>">
		<?php
		 foreach ($columnContents as $contents) :

    		 if (!$contents->isEditable()) {
    		     continue;
    	     }

             $data = null;
             $dataMobile = null;

             foreach ($contents->getData() as $data) {
                if ($data->isMobile()) {
                    $dataMobile = $data;
                }

                if ($data && $dataMobile) {
                    break;
                }
             }

             if ($dataMobile) {
                 if ($column == 'special') {
                     $mobileContent['special'][] = $dataMobile;
                 } else {
                     $mobileContent['main'][] = $dataMobile;
                 }
             }
		?>
		<div id="desktop-<?php echo $data->getContentId(); ?>" class="portlet <?php echo $data->getParent()->getWidget(); ?>">
    		<div class="portlet-header"><?php echo $data->getParent()->getWidget(); ?></div>
    		<div class="portlet-content">
    		    <?php echo $data->getTitle();?>
        		<div class="portlet-tools tools">
        			<input type="hidden" name="content_id" value="<?php echo $data->getContentId(); ?>" />
        			<a class="icon edit"><?php echo $this->translate('captive_content_widget_edit'); ?></a>
        			<a class="icon delete"><?php echo $this->translate('captive_content_widget_delete'); ?></a>
        		</div>
    		</div>
    	</div>
		<?php

		 endforeach;
	     if ($column !== 'special') :
		?>
		<div class="portlet-tools tools">
			<a class="icon add"><?php echo $this->translate('captive_content_widget_add'); ?></a>
		</div>
		<?php
		 endif;
		?>
	  </div>
  <?php
      endforeach;

      /**
       * @todo Get this out of here
       */
      function sortMobileContents($contentA, $contentB) {
        return ($contentA->getOrder() < $contentB->getOrder()) ? -1 : 1;
      }

      usort($mobileContent['main'],'sortMobileContents');
  ?>
  	</div>
  	<div id="mobile">
	<?php
	foreach ($mobileContent as $column => $columnContents) :
      ?>
	  <div id="mobile-column-<?php echo $column; ?>" class="column <?php echo $column; ?> ui-widget ui-widget-content ui-helper-clearfix ui-corner-all span-18 last">
		<?php
	      foreach ($columnContents as $data) :

		      if (!$data->getParent()->isEditable()) {
		          continue;
		      }
		?>
		<div id="mobile-<?php echo $data->getContentId(); ?>" class="portlet <?php echo $data->getParent()->getWidget(); ?>">
    		<div class="portlet-header"><?php echo $data->getParent()->getWidget(); ?></div>
    		<div class="portlet-content">
    		    <?php echo $data->getTitle();?>
        		<div class="portlet-tools tools">
        			<input type="hidden" name="content_id" value="<?php echo $data->getContentId(); ?>" />
        			<a class="icon edit"><?php echo $this->translate('captive_content_widget_edit'); ?></a>
        			<a class="icon delete"><?php echo $this->translate('captive_content_widget_delete'); ?></a>
        		</div>
    		</div>
    	</div>
		<?php
	     endforeach;
	     if ($column !== 'special') :
		?>
		<div class="portlet-tools tools">
			<a class="icon add"><?php echo $this->translate('captive_content_widget_add'); ?></a>
		</div>
		<?php
		 endif;
		?>
	  </div>
      <?php
      endforeach;
	?>
  	</div>
  </div>
</div>